sudo: required

language: java
jdk: 
    - openjdk11
 

branches:
    only:
    - minor
    except:
    - dev 
env:
    global:
      - SHA=$(git rev-parse HEAD)
 
before_install:
      
      - mv frontend-template/dist/* HospitalApp/src/main/resources/static
      - cd HospitalApp
script:

- ./mvnw spring-boot:run
 



