sudo: required

language: java


jdk: 
    - openjdk8

branches:
    only:
    - minor
    except:
    - dev 
env:

 
    
 
 
 before_install:
  
  - mv frontend-template/dist/* HospitalApp/src/main/resources/static
  - cd HospitalApp
   
   
script:
- mvn clean install -DskipTests
