sudo: required
language: java
before_install:
  - chmod +x mvnw
   - mv frontend-template/dist/* HospitalApp/src/main/resources/static
    - cd HospitalApp

jdk: 
    - openjdk8

branches:
    only:
    - minor
    except:
    - dev 
env:
    global:
      - SHA=$(git rev-parse HEAD)
 
    
 
 
   
   
script:
- mvn clean install 
